name: GitHub Metrics

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

      - name: General metrics
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          config_timezone: America/New_York
